// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package define

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine(in *jlexer.Lexer, out *SortFieldSetting) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "field_name":
			out.FieldName = string(in.String())
		case "value":
			out.Value = float64(in.Float64())
		case "key_name":
			out.KeyName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine(out *jwriter.Writer, in SortFieldSetting) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"field_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FieldName))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"key_name\":"
		out.RawString(prefix)
		out.String(string(in.KeyName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SortFieldSetting) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SortFieldSetting) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SortFieldSetting) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SortFieldSetting) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine(l, v)
}
func easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine1(in *jlexer.Lexer, out *FilterFieldSetting) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "field_name":
			out.FieldName = string(in.String())
		case "value":
			if m, ok := out.Value.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Value.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Value = in.Interface()
			}
		case "key_name":
			out.KeyName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine1(out *jwriter.Writer, in FilterFieldSetting) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"field_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FieldName))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if m, ok := in.Value.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Value.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Value))
		}
	}
	{
		const prefix string = ",\"key_name\":"
		out.RawString(prefix)
		out.String(string(in.KeyName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FilterFieldSetting) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FilterFieldSetting) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FilterFieldSetting) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FilterFieldSetting) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine1(l, v)
}
func easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine2(in *jlexer.Lexer, out *DataAgreement) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "doc_id":
			out.DocId = string(in.String())
		case "create_time":
			out.CreateTime = int64(in.Int64())
		case "refs":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Refs = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					v1 = string(in.String())
					(out.Refs)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "many_refs":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ManyRefs = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 string
					v2 = string(in.String())
					(out.ManyRefs)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "sort_fields":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SortFields = make(map[string]*SortFieldSetting)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 *SortFieldSetting
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(SortFieldSetting)
						}
						(*v3).UnmarshalEasyJSON(in)
					}
					(out.SortFields)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		case "filter_field":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.FilterField = make(map[string]*FilterFieldSetting)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 *FilterFieldSetting
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(FilterFieldSetting)
						}
						(*v4).UnmarshalEasyJSON(in)
					}
					(out.FilterField)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "fields":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Fields = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 interface{}
					if m, ok := v5.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v5.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v5 = in.Interface()
					}
					(out.Fields)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine2(out *jwriter.Writer, in DataAgreement) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"doc_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DocId))
	}
	{
		const prefix string = ",\"create_time\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateTime))
	}
	{
		const prefix string = ",\"refs\":"
		out.RawString(prefix)
		if in.Refs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v6First := true
			for v6Name, v6Value := range in.Refs {
				if v6First {
					v6First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v6Name))
				out.RawByte(':')
				out.String(string(v6Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"many_refs\":"
		out.RawString(prefix)
		if in.ManyRefs == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.ManyRefs {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				out.String(string(v7Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"sort_fields\":"
		out.RawString(prefix)
		if in.SortFields == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.SortFields {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				if v8Value == nil {
					out.RawString("null")
				} else {
					(*v8Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"filter_field\":"
		out.RawString(prefix)
		if in.FilterField == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.FilterField {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				if v9Value == nil {
					out.RawString("null")
				} else {
					(*v9Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"fields\":"
		out.RawString(prefix)
		if in.Fields == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v10First := true
			for v10Name, v10Value := range in.Fields {
				if v10First {
					v10First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v10Name))
				out.RawByte(':')
				if m, ok := v10Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v10Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v10Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DataAgreement) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DataAgreement) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson10cd2529EncodeGithubComSimonks2016SubwayDefine2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DataAgreement) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DataAgreement) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson10cd2529DecodeGithubComSimonks2016SubwayDefine2(l, v)
}
